UPLOAD_PAGE = 'https://www.hubs.com/manufacture/'
LOGIN_PAGE = 'https://www.hubs.com/manufacture/login'
TEST_USERNAME = 'kingatest.acc@gmail.com'
TEST_PASSWORD = 'Testingpass@123'
STEP_FILE = '1-1x-6._electronic_enclosure_v11_original-original.step'
JPG_FILE = 'test.jpg'
DXF_FILE = 'circle.dxf'
IGES_FILE = 'iges_one.iges'
SAT_FILE= 'sat_one.sat'
DIALOG_WELCOME_STRING = 'Welcome to Hubs!'
DIALOG_PARAGRAPH_STRING = 'To view your instant quote, simply sign up with your work email address or '
NOT_SUPPORTED_MESSAGE = 'files are not supported. Please upload your parts in one of the following formats: STL, OBJ, ' \
                        'STEP, STP, IGES, IGS, SLDPRT, 3DM, SAT, X_T or DXF.'
QUOTE_OVERVIEW_TITLE = 'Quote overview'
